### ISSUE TITLE
I've implemented a similiar algorithm, but with private-use codepoints.

### ISSUE THREAD

**Issue by morganwahl** [qntm/base65536#13]
Hello, I didn't see any other way of contacting you other than opening an issue.

After reading about your work here, I was inspired to do my own variation using private-use codepoints. It's here: https://github.com/morganwahl/base-private-use

I checked and Twitter does seem to leave private-use characters alone (as it should).

Since I had the luxury of two whole planes to work with, I decided to define a way to encode arbitrary bit sequences, not just ones that are byte padded. This was partly with HATETRIS replays in mind.

Finally, since these codepoints are meant to be used for this sort of thing, you could (in theory) generate a font that when installed would render HATETRIS replays encoded with this scheme as some series of symbols of the actual moves!

Hope you find this interesting.

-Morgan

**Comment by qntm** [comment]
Very nice, thank you.

**Comment by RainbowAsteroids** [comment]
Is this better than base65536?

**Comment by qntm** [comment]
It depends what you want it to be good at.
