### ISSUE TITLE
Not able to install package in Cloud 9

### ISSUE THREAD

**Issue by redbrain1014** [qntm/base65536#17]
I use [Cloud 9](https://c9.io) for developing in Node.js. I tried to install your package, but it failed. Error log:
![error log feb9](https://user-images.githubusercontent.com/42494361/52824135-7a2c0680-3085-11e9-919c-9a8857e3dbf7.jpg)
Any idea why I cannot install it?

**Comment by qntm** [comment]
Those are just warnings, not errors. Installation completed successfully.
