### ISSUE TITLE
Issue importing the module

### ISSUE THREAD

**Issue by Rapiiidooo** [qntm/base65536#21]
I'm using angular 9 and I really don't get what is happening.

`import { encode, decode } from 'base65536';`

That is how I imported the module.

`const test = encode(uint8array);`

That is how I used it.

And I get this error: 
`TypeError: Object(...) is not a function`

Assume that uint8array has the correct type because it has.

**Comment by qntm** [comment]
Can you provide full steps for reproducing the error? None of your example code involves Angular 9.

**Comment by Rapiiidooo** [comment]
https://stackblitz.com/edit/angular-eoyerl?file=src%2Fapp%2Fapp.component.ts

**Comment by qntm** [comment]
Looks like `base65536` has run afoul of this: https://github.com/webpack/webpack/issues/4674

**Comment by qntm** [comment]
@Rapiiidooo Give `base65536@3.0.2` a whirl.

**Comment by Rapiiidooo** [comment]
Fixed in base65536@3.0.2 great job and thank you very much :)
