### ISSUE TITLE
package.json "main" field deprecation warning

### ISSUE THREAD

**Issue by nightori** [qntm/base65536#51]
When base65536 is imported as an ES6 module, a deprecation warning appears in the console:

```
[DEP0151] DeprecationWarning: Package ...\node_modules\base65536\ has a "main" field set to "src", excluding the full filename and extension to the resolved file at "src\index.js", imported from...
Automatic extension resolution of the "main" field is deprecated for ES modules.
```

When I change it from "src" to "src/index.js", no warning appears. Is there a reason why it's set to "src" instead of "src/index.js"?

**Comment by qntm** [comment]
Try `base65536@4.0.2`.
